name: 📦 Build, push and deploy release

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]

jobs:
  extract:
    name: 📄 Extract
    uses: anthonypillot/actions/.github/workflows/extract-version.yaml@v1

  build:
    name: 🏗️ Build
    uses: anthonypillot/actions/.github/workflows/node-build-and-test.yaml@v1
    with:
      run_test: true
      run_lint: true

  push:
    name: 🐳 Push
    needs: [extract, build]
    uses: anthonypillot/actions/.github/workflows/node-build-image-and-push.yaml@v1
    with:
      registry_url: ghcr.io
      registry_username: ${{ github.repository_owner }}
      image_owner: ${{ github.repository_owner }}
      image_name: os
      image_tag: ${{ needs.extract.outputs.result }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: 🚀 Deploy
    needs: [extract, push]
    strategy:
      matrix:
        include:
          - environment: production
            namespace: os-prod
            shortcut: prod
          - environment: pre-production
            namespace: os-prep
            shortcut: prep
    uses: anthonypillot/actions/.github/workflows/kubernetes-deployment.yaml@v1
    with:
      registry_url: ghcr.io
      registry_username: ${{ github.repository_owner }}
      environment: ${{ matrix.environment }}
      namespace_name: ${{ matrix.namespace }}
      deployment_name: os-${{ matrix.shortcut }}
      image_name: os
      image_tag: ${{ needs.extract.outputs.result }}
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
